source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VerticallyScrollingStatusView_Example', :exclusive => true do
  pod "VerticallyScrollingStatusView", :path => "../"
end

target 'VerticallyScrollingStatusView_Tests', :exclusive => true do
  pod "VerticallyScrollingStatusView", :path => "../"

  
end
